INSERT INTO produtos (nome, descricao, preco, estoque, idCategoria) VALUES
('Culpa Adipisci', 'Quae sint repellendus distinctio reprehenderit earum error error.', 4470.17, 128, 5),
('Quis Mollitia', 'Dolor atque magni quibusdam dicta non.', 602.6, 148, 3),
('Quae Facilis', 'Facere libero magni odio nesciunt qui vero porro eos.', 2183.99, 137, 1),
('Nihil Beatae', 'Praesentium ipsa omnis a nostrum et eveniet.', 3527.26, 128, 1),
('Quibusdam Maiores', 'Ab assumenda at cumque et deserunt officia maiores similique deleniti.', 3479.07, 26, 5),
('Accusamus Molestias', 'Vitae voluptate earum vero consequuntur rerum.', 2939.57, 89, 3),
('Suscipit Tempore', 'Sequi illum tempore hic ex adipisci dolorem nesciunt.', 645.39, 183, 2),
('Tempore Fugit', 'Architecto dolore eius nisi at ratione natus.', 3660.44, 140, 4),
('Quas Aut', 'Tempore explicabo eligendi debitis distinctio ex sed itaque sint.', 1999.43, 31, 3),
('Animi Quo', 'Minus fugit similique ea error tempora neque explicabo repudiandae beatae minima eum.', 2769.49, 30, 5),
('Praesentium Nostrum', 'Enim sunt quas nostrum laborum at porro quas iure labore tempora.', 3038.26, 173, 4),
('Perferendis Voluptas', 'Accusamus aliquid occaecati quas esse nobis cumque doloremque fugiat.', 1367.29, 66, 1),
('Voluptate Amet', 'Sunt dolores officia nam veniam laudantium laborum culpa delectus distinctio velit reiciendis aliquid.', 2017.3, 124, 4),
('Cumque Cum', 'Officia deleniti harum veniam maxime illo vel assumenda sequi.', 397.34, 155, 5),
('Molestiae Distinctio', 'Necessitatibus eaque recusandae qui quos enim voluptatum inventore cupiditate occaecati ullam.', 1421.82, 18, 3),
('Soluta Odit', 'In neque nemo numquam aliquam cupiditate minus quo.', 1440.19, 50, 4),
('Minima Ex', 'Voluptatibus a mollitia aliquam minima commodi autem accusamus odio nisi quis quis architecto.', 2595.33, 94, 4),
('Repellendus Similique', 'Perspiciatis tempore aut fuga quisquam porro non distinctio eveniet at fuga eligendi.', 2329.53, 101, 1),
('Reprehenderit Eum', 'Ratione quod nobis laboriosam molestias nisi possimus inventore laborum quas atque vero repellat.', 2806.06, 28, 4),
('Quo Eos', 'Odit eaque alias velit quis fuga omnis accusantium ea officiis.', 306.41, 24, 2),
('Aliquid Sed', 'Voluptatibus molestiae aspernatur doloribus inventore voluptatem commodi quis id dolorum molestiae.', 13.88, 29, 3),
('Corrupti Culpa', 'Ratione voluptate expedita expedita molestias saepe doloremque.', 2980.02, 72, 1),
('Accusantium Minima', 'Dicta rem neque magni numquam at nam delectus sint sunt molestias.', 1979.05, 145, 5),
('Libero Expedita', 'Animi commodi unde incidunt hic earum.', 4613.49, 188, 3),
('Animi Velit', 'Nam voluptatibus tempora modi sit blanditiis ipsa accusantium sapiente consectetur quibusdam.', 3039.23, 28, 3),
('Sint Quaerat', 'Recusandae fugiat consequuntur optio cupiditate beatae natus quam at est assumenda omnis.', 2962.58, 75, 4),
('Dolores Culpa', 'Fuga assumenda iure modi et quibusdam nobis.', 882.73, 122, 2),
('Recusandae Sit', 'Itaque vitae saepe soluta eum odio earum doloremque nulla illo commodi.', 1652.57, 144, 2),
('Voluptatem Enim', 'Consectetur nam laudantium distinctio error officiis quos ut veniam earum modi.', 3957.76, 168, 1),
('Deleniti Totam', 'Culpa quis quae et quas accusamus error aliquid consequatur enim a magnam quam.', 3167.81, 198, 4),
('Aliquid Provident', 'Vitae explicabo eos assumenda assumenda odio adipisci illum alias atque ad perspiciatis deleniti.', 260.98, 34, 5),
('Nobis Atque', 'Repellendus pariatur consectetur reprehenderit molestias rerum quasi dignissimos qui corporis harum voluptatem.', 2669.09, 67, 3),
('Nam Enim', 'Deleniti cupiditate nesciunt molestiae quis itaque possimus iure voluptates quisquam.', 3270.69, 177, 2),
('Deleniti Eum', 'Aliquam et at repellendus minima eos deleniti inventore.', 3729.54, 27, 2),
('Dolores Sunt', 'Consequuntur sint sunt reprehenderit architecto totam inventore ipsam quos veritatis.', 2821.95, 124, 3),
('Nostrum Ex', 'Dolore beatae saepe asperiores cupiditate fuga similique.', 1299.14, 94, 3),
('Porro Optio', 'Quia maiores dolores cupiditate atque tempore odit delectus accusantium cum.', 2109.3, 112, 3),
('Soluta Modi', 'Magnam quasi ut necessitatibus ea voluptatibus a cupiditate assumenda.', 1103.65, 20, 4),
('Aspernatur Id', 'Voluptatem odit ad odit aliquid tempore molestiae quia inventore.', 3097.2, 157, 2),
('Labore Accusantium', 'Minima possimus ex animi deserunt similique deleniti reprehenderit distinctio eveniet adipisci.', 3385.23, 80, 1),
('Rerum Quis', 'Rem sunt ut veniam delectus fugiat quibusdam impedit odio iusto ipsa earum reiciendis.', 807.06, 129, 2),
('Sunt Nobis', 'Tenetur consequatur voluptates nesciunt animi illo ullam vitae quo.', 75.43, 56, 2),
('Ipsum Magnam', 'Voluptas placeat quibusdam sed cum tempora.', 1630.5, 20, 5),
('Hic Animi', 'Architecto soluta quasi modi veritatis dolorum suscipit harum temporibus assumenda.', 2446.21, 151, 5),
('Cupiditate Veniam', 'Vitae nulla accusamus quis nam quibusdam placeat officia porro itaque nulla vel.', 1258.37, 197, 3),
('Vitae Itaque', 'Consequuntur qui expedita doloribus sit adipisci.', 678.45, 70, 4),
('Consequuntur Provident', 'Quasi dolores esse tempore eligendi debitis expedita.', 3528.49, 198, 1),
('Nemo Officia', 'Accusamus nemo culpa earum nemo nostrum ducimus.', 749.6, 60, 5),
('Quasi Labore', 'Impedit nobis consequuntur iusto recusandae unde placeat repellat quod.', 614.61, 165, 1),
('Sequi Deleniti', 'Amet tempore sint voluptate id voluptatem laboriosam enim.', 479.98, 169, 1);